actors:
  ganezasan:
    image_url: https://pbs.twimg.com/profile_images/1037883635297181696/k66KggwR_400x400.jpg
    name: Taka
    url: https://twitter.com/ganezasan
  otukutun:
    image_url: https://avatars3.githubusercontent.com/u/1199643?s=400&v=4
    name: おつくつん
    url: https://twitter.com/otukutun
author: ganezasan
description: 週末ラヂオでは週末開発しているTakaとおつくつんの雑談を収録しています。とってもゆるいラヂオです。
description_long: 週末ラヂオでは週末開発しているTakaとおつくつんの雑談を収録しています。とってもゆるいラヂオです。
email: info@shumatsu.life
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: shumatsu_life
itunes_podcast_url:
keywords: 週末ラヂオ,ganezasan,otukutun,個人開発,個人プロダクト,NativeCamp,"Hi Native"
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 週末ラヂオ
github:
  url: https://shumatsu.life
g_tracking_id: UA-30870234-11
